name:                cnc-pattern-lib
version:             0.1.0.0
github:              "mazelife/cnc-pattern-lib"
license:             BSD3
author:              "James Stevenson"
maintainer:          "james.m.stevenson (Î») gmail (dot) com"
copyright:           "James Stevenson"

extra-source-files:
- README.rst
- .hlint.yaml

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mazelife/cnc-pattern-lib#readme>

dependencies:
- base >= 4.7 && < 5
- blaze-markup == 0.8.2.3
- blaze-svg == 0.3.6.1
- containers == 0.6.0.1
- HUnit == 1.6.0.0
- text == 1.2.3.1
- pretty-show == 1.9.5
- optparse-applicative == 0.14.3.0
- hmatrix == 0.20.0.0

ghc-options:
- -Wall
- -fwarn-tabs
#- -Werror
- -funbox-strict-fields


library:
  source-dirs: src

default-extensions: 
- OverloadedStrings 
- PatternSynonyms

executables:
  cnc-pattern-lib:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cnc-pattern-lib

tests:
  cnc-pattern-lib-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cnc-pattern-lib
    - HUnit-approx == 1.1.1.1
    - tasty == 1.2.3
    - tasty-hunit == 0.10.0.2
